# Generated by Django 4.2.29 on 2026-03-06 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_embedding_created_at_face_confidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='avg_embedding',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='face_count',
            field=models.IntegerField(default=0),
        ),
    ]
