# Generated by Django 4.2.29 on 2026-03-06 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_person_avg_embedding_person_face_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='clip_embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
